Fix bug to prevent dragging out of document
Annotato/annotato pull request #70
Opened 2022-03-21 13:07 UTC by darren2pro

2022-03-21 13:13 UTC, darren2pro commented
Resolves #46

2022-03-21 13:31 UTC, ganhongyao requested changes
Would it be better if we allow the annotation to be dragged back in from outside, instead of blocking the annotation from being dragged out?

2022-03-21 13:31 UTC, ganhongyao commented on Annotato/Annotato/Views/Document/Edit/Annotation/AnnotationView.swift
> +        if hasExceededTop || hasExceededBottom || hasExceededLeft || hasExceededRight {
Can we abstract this bounds-checking out into a function in a `UIView` extension so that it can be reused by other views in future? 

i.e. something like 
`func hasExceededBounds(bounds: CGRect) -> Bool`

2022-03-21 13:36 UTC, darren2pro commented on Annotato/Annotato/Views/Document/Edit/Annotation/AnnotationView.swift
> +        if hasExceededTop || hasExceededBottom || hasExceededLeft || hasExceededRight {
Ok sounds good

2022-03-21 13:37 UTC, zognin reviewed
- Users can still tap the edge of the pdf and an annotation is created there.

![photo_2022-03-21 21 35 10](https://user-images.githubusercontent.com/71375383/159272156-78d832b6-a948-41fc-886b-9fb9117ac521.jpeg)

- I think checking of bounds may be domain logic --> model layer. However, to keep it simple we can leave it in the view layer for now.

2022-03-21 13:37 UTC, zognin commented on Annotato/Annotato/Views/Document/Edit/Annotation/AnnotationView.swift
> +        let currentCenter = viewModel.center
Would previousCenter sound clearer? Because the center is changed afterwards
```suggestion
        let previousCenter = viewModel.center
```

2022-03-21 13:37 UTC, zognin commented on Annotato/Annotato/Views/Document/Edit/Annotation/AnnotationView.swift
> +        let hasExceededTop = frame.minY < 0
```suggestion
        let hasExceededTop = frame.minY < superview.bounds.minY
```

2022-03-21 13:37 UTC, zognin commented on Annotato/Annotato/Views/Document/Edit/Annotation/AnnotationView.swift
> +        let hasExceededLeft = frame.minX < 0
```suggestion
        let hasExceededLeft = frame.minX < superview.bounds.minX
```

2022-03-22 16:20 UTC, zognin approved these changes
LGTM thanks

2022-03-22 16:21 UTC, merged